/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

var findTheDifference = function(s, t) {
    //Create a character map to store characters from the longer string.
    let charMap = {};
    
    //Populate the character map.
    for(let i = 0; i < t.length; i++) {
        if(charMap[t[i]]) {
            charMap[t[i]]++;
        } else {
            charMap[t[i]] = 1;
        }
    }
    
    //Look at each character in the shorter string.
    for(const character of s.split("")) {
        //Remove this instance of this character from the character map.
        charMap[character]--;
    }
    
    //Return which ever characteris left over.
    for(const character in charMap) {
        if(charMap[character]) return character;
    }
    
    //Only adding this line for use in GitHub project (if user does not input according to constraints)
    return "";
};